### ISSUE TITLE
Windows XP x86 Support

### ISSUE THREAD

**Issue by deadcast2** [n64dev/cen64#117]
Hi! I've been struggling for the past couple of days to build a 32bit version of cen64 for Windows XP. I can compile successfully using MSYS2/GCC but get an "illegal instruction" when running the executable on a XP machine. The binary does run fine on my local x64 Win 10 computer.

Is this even possible to do lol? I may be just wasting time but I'm curious to see. :0) I'm building a new game engine for the N64 and wanted to integrate your emulator so people can preview their results quickly.

Thanks!

**Comment by deadcast2** [comment]
Well I managed to butcher the code enough to get the emulator(VirtualBox 6) to finally run a rom. Results...

![test-scene](https://user-images.githubusercontent.com/45521946/51224747-387c3480-18fc-11e9-8cf5-7d190c839531.PNG)

Haha as you can see it's pretty messed up and sluggish. Fun learning more about intrinsics but I think my endeavor may be futile. I have a x64 version of Win XP coming soon and I'll try another normal build to test out. Maybe that will give some different results but not sure. :0)

**Comment by deadcast2** [comment]
It appears the rendering issue is coming from having too low of an opengl version on my virtual machine. I have support up to OGL 2.1. I'm going to add some gl debugging code to see if I can pinpoint the exact issue. If I can find it then maybe I'll have an okay running 32bit version of cen64! :0)

**Comment by deadcast2** [comment]
Hello again! Got the issue finally sorted. I'm probably wrong but I think there's a bug in my old OpenGL 2.1 driver that is not setting the byte swapping for the frame buffer:

https://github.com/n64dev/cen64/blob/b27960c94f9f4d5997fc2b64a76fb30e79b13be4/vi/render.c#L46
I fixed by just manually rolling my own byte swapper and now all is good! ^_^

https://github.com/deadcast2/cen64/blob/cd8ae9c48a150d0b9121d4c38a82ea019680b4f4/vi/controller.c#L135

![capture](https://user-images.githubusercontent.com/45521946/51655859-59273880-1f53-11e9-8030-de4360969247.PNG)

Happy pipe now :D

![fixed](https://user-images.githubusercontent.com/45521946/51655878-6cd29f00-1f53-11e9-820d-80464dd39566.PNG)

**Comment by MoochMcGee** [comment]
Why would you even WANT XP support? It's been dead for almost 5 years at this point, fucking let it GO already.

**Comment by commandtab** [comment]
Perhaps because the Nintendo 64 SDK kit runs well under XP, so it's convenient to be able to compile homebrew and immediately run it under cen64 all in the same VM?

**Comment by deadcast2** [comment]
@MoochMcGee 

Well, I would love to let it go as you say but the reasoning behind running on XP is due to my new engine/level editor I'm building for the console. Since my new tooling relies on 16bit executable for ROM compilation, getting those reverse-engineered to operate on modern architecture would be a bit daunting for me now (Wine and DosBox both fail to run those executables). I'm creating a Unity3D-like tool that will let others quickly setup a 3d scene, hit build & run and then be able to see the results immediately. People can even choose to run on a real console as well.

So maybe someday I'll have enough time to devote to constructing a new ROM producer but for now XP/NT/2000 are a way for me to continue making good progress. :)

**Comment by deadcast2** [comment]
@commandtab 
> 
> 
> Perhaps because the Nintendo 64 SDK kit runs well under XP, so it's convenient to be able to compile homebrew and immediately run it under cen64 all in the same VM?

Yes! That's exactly my reasoning behind using XP as a starting development OS. I would love not to use it but only so many things to solve at once lol. :D

**Comment by deadcast2** [comment]
Here's the tool I'm working on BTW https://github.com/deadcast2/UltraEd :)

**Comment by jkbenaim** [comment]
Hey @deadcast2 - just wanted to say that while any of the maintainers are unlikely to work on XP support any time soon, I have definitely taken notice and I think this is pretty cool.

If you haven't already, you might consider publishing the changes you made to get CEN64 building under XP.

Good luck with your project! :D

**Comment by deadcast2** [comment]
Hi @jkbenaim! Thanks so much! Haha I'm gonna need it. ^_^
