### ISSUE TITLE
cen64.com uses an expired certificate

### ISSUE THREAD

**Issue by cam1170** [n64dev/cen64#121]
I'm not an expert on security certificates, but when I went to the website and Firefox displayed a message that there was a "Potential Security Risk Ahead", I was concerned.

The certificate began on March 23, 2018 and expired on June 21, 2018 and was apparently issued by "Let's Encrypt Authority X3". I don't know who runs the website, nor do I know about the state of this emulator's development, but this seems like an issue to me. Whatever can be done to improve the situation would be awesome, thanks.

**Comment by jkbenaim** [comment]
@tj90241 he's not wrong bruh fix ittttttt

**Comment by cam1170** [comment]
I'm new to github, it says I closed the issue but I don't think I did, what happened?

**Comment by dxgldotorg** [comment]
It's still expired; Let's Encrypt certificates have to be renewed at least once every 90 days.

**Comment by cam1170** [comment]
Looks good now
