### ISSUE TITLE
Failed to allocate enough memory for a device.

### ISSUE THREAD

**Issue by w3bb** [n64dev/cen64#128]
I can't seem to run any N64/N64DD games because of this error. This is the output of Cen64:
```
Using NTSC-U PIFROM
Detected cart: NSM[EJP] - Super Mario 64
Failed to allocate enough memory for a device.
```
I'm running Void Linux (x64).

**Comment by mikeryan** [comment]
Can you provide the full command line that you used?

**Comment by w3bb** [comment]
Here ya go:
```
cen64 -ddipl [file location] -ddrom [Mario Artist Polygon Studio Rom] [pifdata.bin location]
```
I also tried using the flash option, the various memory options, and checking the files for corruption. The files work perfectly fine on MAME, and I tried swapping them out from another source to no change.

**Comment by tj90241** [comment]
Are you using Windows or Linux?  If Linux, what is the output of

```
grep -i huge /proc/meminfo
```

**Comment by w3bb** [comment]
@tj90241 
```
[webb@silk ~]$ grep -i huge /proc/meminfo
AnonHugePages:         0 kB
ShmemHugePages:        0 kB
HugePages_Total:       0
HugePages_Free:        0
HugePages_Rsvd:        0
HugePages_Surp:        0
Hugepagesize:       2048 kB
Hugetlb:               0 kB
```

**Comment by tj90241** [comment]
hmmm... `ulimit -a` too?  Which distro is this?

**Comment by w3bb** [comment]
@tj90241 Here ya go:
```
core file size          (blocks, -c) 0
data seg size           (kbytes, -d) unlimited
scheduling priority             (-e) 0
file size               (blocks, -f) unlimited
pending signals                 (-i) 30699
max locked memory       (kbytes, -l) 1024
max memory size         (kbytes, -m) unlimited
open files                      (-n) 1024
pipe size            (512 bytes, -p) 8
POSIX message queues     (bytes, -q) 819200
real-time priority              (-r) 0
stack size              (kbytes, -s) 8192
cpu time               (seconds, -t) unlimited
max user processes              (-u) 30699
virtual memory          (kbytes, -v) unlimited
file locks                      (-x) unlimited
```

**Comment by jkbenaim** [comment]
Tried this myself on Void. It looks like mmaping with both PROT_WRITE and PROT_EXEC will fail with `-1 EPERM (Operation not permitted)`.
I'm not familiar enough with Void to say if there's a way around this. I poked around to see if PaX, AppArmor, SELinux, etc. were blocking it, but couldn't find any of them in the default install.
Maybe an experienced Void user would know.

**Comment by jkbenaim** [comment]
Fixed this issue with a recent commit. However, another issue seems to be preventing cen64 from coming up on void/musl. Investigating...
