### ISSUE TITLE
Super Mario 64 wrong lighting

### ISSUE THREAD

**Issue by Mastergatto** [n64dev/cen64#136]
Maybe it's due to unimplemented LTV/STV opcodes...?
(first screen is CEN64 obviously, the second screen is mupen64plus with angrylion RDP plus)

![sm1-cen64](https://user-images.githubusercontent.com/1028191/68254962-3ff80000-002c-11ea-86a9-79aaac857f5a.png)
![super_mario_64-002](https://user-images.githubusercontent.com/1028191/68254996-4dad8580-002c-11ea-934c-459d874f322e.png)

![sm2-cen64](https://user-images.githubusercontent.com/1028191/68254970-425a5a00-002c-11ea-9f0f-24c164bfd387.png)
![super_mario_64-003](https://user-images.githubusercontent.com/1028191/68255002-52723980-002c-11ea-982d-ac1f8488c4e3.png)

**Comment by Mastergatto** [comment]
I don't know if this helps, but for what it is worth:
`/* ============================================================================
 *  Instruction: LTV (Load Transpose into Vector Register)
 * ========================================================================= */
void
RSPLTV(struct RSP *rsp, uint32_t rs, uint32_t unused(rt)) {
  const struct RSPRDEXLatch *rdexLatch = &rsp->pipeline.rdexLatch;
  struct RSPEXDFLatch *exdfLatch = &rsp->pipeline.exdfLatch;

  unsigned element = rdexLatch->iw >> 7 & 0xF;
  unsigned dest = rdexLatch->iw >> 16 & 0x1F;
  unsigned offset = rdexLatch->iw & 0x7F;
  offset |= -(offset & 0x0040);

  assert((dest & 7) == 0 && "STV: Invalid `vt` for transpose specified.");

  exdfLatch->memoryData.target = &rsp->cp2.regs[dest];
  exdfLatch->memoryData.function = &LoadTransposeVector;
  exdfLatch->memoryData.offset = rs + (offset << 4);
  exdfLatch->memoryData.element = element;
  exdfLatch->memoryData.cp2 = &rsp->cp2;
}
`

**Comment by tj90241** [comment]
Yes, it's due to `LTV` and `STV`.  The new core implemented all the RSP vector coprocessor instructions using SSE intrinstics, but these two instructions not really amenable to SSE from what I recall.  You could probably make do with the implements above - neat to see that someone still has a copy of CEN64's earlier years lying around.

**Comment by Mastergatto** [comment]
Maybe I could, but I know nothing about C and the N64 architecture...:( Maybe someone brave can come forward and try to implement those opcodes...:P
I have uploaded the older to: https://github.com/Mastergatto/cen64-old

**Comment by sp1187** [comment]
Fixed by b08188f3889ae914cb1dcffb179c5656571b0e2b.

**Comment by Mastergatto** [comment]
Nice, it has fixed Super Mario 64, OoT, Pokèmon Stadium 2 and partially Resident Evil 2. Excellent job!
