### ISSUE TITLE
DRAM -> DMEM dmas don't align to 8 byte boundaries

### ISSUE THREAD

**Issue by joeldipops** [n64dev/cen64#140]
I was using a script similar to the below (incorrect) RSP code to move some data in to DMEM.  When testing with Cen the code was working fine, but when I tried it on my n64, I found the data was offset.  This is because this kind of DMA requires 8byte alignment and seems to AND any non-aligned address back to an aligned one.  Cen64 does not emulate this behaviour at the moment.

```
    # Set source.
    lui $t0, 0x8004
    addi $t0, $t0, 0x1000
    mtc0 $t0, $DMA_DRAM

    # Set destination
    addi $t0, $0, 0x0B0C
    mtc0 $t0, $DMA_DMEM

    # set length (which kicks off DMA)
    addi $t0, $0, 0x10 - 1
    mtc0 $t0, $DMA_IN_LENGTH

    # wait for DMA to complete
    3:
        mfc0 $t0, $DMA_BUSY
    bne $t0, $0, 3b
    nop

    # DMA destination address actually 0x0B08!

    # Where are my first four bytes?
    lhu $t0, 0x0B0C($0)

    ... 
    # etc
```

**Comment by sp1187** [comment]
Should be fixed by https://github.com/n64dev/cen64/commit/eb935a85f78bf2aa879e8f29fbdaa6850a264579.
