### ISSUE TITLE
Can you guys port this to RG350?

### ISSUE THREAD

**Issue by jserodio** [n64dev/cen64#156]
I see Mugen 64 has been ported to RG350 but the performance is super low.
This emulator for N64 seems to be more updated, is there any chance we can this emulatored ported to this console?

https://github.com/retrogamehandheld/RG-350/wiki

Regards

**Comment by jkbenaim** [comment]
The chance of cen64 running well on that hardware is absolutely zero. It would be a lot of work to get it to run at all.

Sorry friend. Closing this issue as it's basically impossible.
