### ISSUE TITLE
tlb_probe returns wrong miss for an existing but marked invalid entry

### ISSUE THREAD

**Issue by clbr** [n64dev/cen64#176]
1. App sets a TLB entry for address 0, NULL, as invalid.
2. App tries to access virtual address NULL.
3. cen64 fires a DTLB exception with miss=1 invalid=1. It should fire a miss=0 invalid=1 since the entry exists.

This causes the wrong exception handler to be called, resulting in an infinite loop in the app.

**Comment by clbr** [comment]
It appears the x86_64 tlb_probe has buggy logic. It treats the valid bit as "entry can be matched", not as what it's supposed to be - "this address is invalid but exists".

**Comment by tj90241** [comment]
This seems to have been a gross understanding on my behalf when I had written the code long ago, indeed lines up with the lingo in the documentation:

```
If there is no TLB entry that matches the virtual address, a TLB miss exception occurs.*  If the access control bits (D and V) indicate that the access is not valid, a TLB Modification exception or TLB Invalid exception occurs.
```

A quick fix seems easy - simply commenting out the two lines that do the valid check should suffice? Doing so fixes #78 ...

One could also remove the "valid" state that were being used to parallelize the lookups with SSE as well.  It does leave open the question of how multiple matching VPNs are handled, though the documentation just suggests "that's undefined".  I'm still wondering if I'm missing something here, or if the hardware needs to be initialized with non-zero values for the VPNs or something.

**Comment by clbr** [comment]
Yes, commenting the two lines
```
//    check_v = _mm_loadl_epi64((__m128i*) (tlb->valid + i));
//  check = _mm_and_si128(check, check_v);
```
was enough to make my case work.

**Comment by sp1187** [comment]
Fixed by https://github.com/n64dev/cen64/commit/6f9f5784bf0a720522c4ecb0915e20229c126aed.
