### ISSUE TITLE
installer does nothing/crashes?

### ISSUE THREAD

**Issue by jeffythedragonslayer** [n64dev/cen64#210]
Hi, the cen64 installer doesn't appear to do anything for me, or is immediately crashing:

> 
> C:\Users\User\Downloads>cen64-windows-x86_64.exe
> 
> C:\Users\User\Downloads>

**Comment by werkn** [comment]
@jeffythedragonslayer I've had this issue if I didn't have OpenGL setup and/or OpenAL.

**Comment by jeffythedragonslayer** [comment]
Oh, I haven't dumped pifdata.bin yet - and I've since heard this isn't an installer but the actual cen64 binary.  Still, an error message would be better than a crash.
