### ISSUE TITLE
JPEG μcode broken

### ISSUE THREAD

**Issue by jkbenaim** [n64dev/cen64#23]
![cen64-jpegucode](https://cloud.githubusercontent.com/assets/2214896/12541445/2fba0054-c2e5-11e5-96e2-2a6ea74cb9e0.png)

The JPEG μcode appears to be broken.

**Comment by emukidid** [comment]
I made it into the screenshot, yay.

**Comment by sp1187** [comment]
Fixed by b08188f3889ae914cb1dcffb179c5656571b0e2b.
