### ISSUE TITLE
Build Issue

### ISSUE THREAD

**Issue by KT7000** [n64dev/cen64#234]
I followed the READ ME instructions and for #5 I extracted the libiconv folder to this directory 
"MSYS\home\yourname\libiconv"

But when I open MSYS and type "cd libiconv", I get a message saying no such file or directory.

**Comment by PeterLemon** [comment]
Hi I just tested latest cen64 source compiles with latest GCC 13 & MSYS 1, & built the libiconv lib from scratch. When MSYS is created it should make a "MSYS\home\yourname\" directory, where "yourname" is your user name in windows, if you navigate to that directory you should see what I mean, I hope the only problem is that you created a "yourname" directory maybe?
Anyway I will put links to the latest GCC 13 pack I just used to build cen64 in step 2 & try to make things more clear in the readme.
