### ISSUE TITLE
IA-32: Build failure with gcc.

### ISSUE THREAD

**Issue by orbea** [n64dev/cen64#42]
OS: `Slackware-current`
`gcc-5.3.0-i586-3`

To see if issue https://github.com/tj90241/cen64/issues/41 was restricted to x86_64 or not I tried to build cen64 again in a clean Slackware64-current chroot, the issue persisted. So I tried again in a Slackware-current chroot (x86) and ran into a new issue...

Build.

```
mkdir -p build
cd build
  cmake \
    -DCMAKE_C_FLAGS:STRING="-O2 -march=i486 -mtune=i686" \
    -DCMAKE_INSTALL_PREFIX=/usr \
    -DCMAKE_BUILD_TYPE=Release ..
  make
  make install DESTDIR=$PKG
cd ..
```

Error.
Full log - http://pastebin.com/JgwG1qu1

```
CMakeFiles/cen64.dir/build.make:254: recipe for target 'CMakeFiles/cen64.dir/bus/controller.c.o' failed
make[2]: *** [CMakeFiles/cen64.dir/bus/controller.c.o] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/cen64.dir/all' failed
make[1]: *** [CMakeFiles/cen64.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by tj90241** [comment]
IA-32 builds aren't supported at the moment due to the fact that one or two SSE intrinsics that CEN64 uses are not available outside of x64. I suppose it should be fixed, though, so I'll leave this up as a reminder to myself.

**Comment by orbea** [comment]
Alright, thanks for the explanation. Feel free to close this issue whenever you feel is best.
