### ISSUE TITLE
Texture glitches and TLB Exception in Paper Mario

### ISSUE THREAD

**Issue by queueRAM** [n64dev/cen64#70]
During the opening sequence of a new game in Paper Mario, Mario's textures looks glitched.
![image](https://cloud.githubusercontent.com/assets/129774/25879145/96deaeaa-34f5-11e7-8b76-19b8d290b46e.png)

Not too many frames later and the game experiences a TLB exception it can't handle. Fortunately, the game appears to have a nice built-in error screen with some useful info.
![image](https://cloud.githubusercontent.com/assets/129774/25879215/fa00056a-34f5-11e7-9704-50e7634c894d.png)

Most commonly, the PC is 802dcf0c, but not always. The culprit instruction at 802dcf0c was `lw v0, 0x0(s1)`. Looking at the value of `s1` in other N64 emulators, I never see anything outside of the 0x803XXXXX range.

**Comment by tj90241** [comment]
This game uses TLB/virtual addresses out of kseg (statically mapped physical memory) like most games do. The `$s1` register could plausibly contain a "valid address" - can't tell without more context/debugging. I've unfortunately wanted to get to the bottom of this bug for awhile but haven't invested the proper time.

**Comment by sp1187** [comment]
This seems to be fixed by https://github.com/n64dev/cen64/commit/9316569eff81721ae32a4cd270ecaf60152fb3a2, closing.
