### ISSUE TITLE
Taz Express missing letters

### ISSUE THREAD

**Issue by Mastergatto** [n64dev/cen64#86]
![tazexpress](https://user-images.githubusercontent.com/1028191/36629706-08604d38-195a-11e8-9fc8-9e23ac73bf57.png)

According to loganmc10, it's caused by unaligned PI DMA access, [see here](https://github.com/project64/project64/issues/633#issuecomment-368156024) for more details. Although the case is for Project64 and mupen64plus, it may be relevant for CEN64 too, as you can see in the image attached here above.

**Comment by tj90241** [comment]
Interesting... this is admittedly something I have given little attention to, so no surprise there.

**Comment by LegendOfDragoon** [comment]
This is caused by PI DMA address not being aligned.

**Comment by parasyte** [comment]
I've created a series of test ROMs that show this bug (PI DMA with unaligned cartridge address) as well as related bugs with byte and halfword reads from the cartridge domain virtual address:

[test-cartridge-read.zip](https://github.com/n64dev/cen64/files/3189852/test-cartridge-read.zip)

These each read 8 bytes from the cartridge header name field (which is set to `abcdefghijkl`) using various methods and asserts on various expectations:

# test-cartridge-byte.n64

```
Reads 8 bytes from virtual address `0xb000_0020`
Expects: `abefefij`
```

# test-cartridge-halfword.n64

```
Reads 4 halfwords from virtual address `0xb000_0020`
Expects: `abefefij`
```

# test-cartridge-word.n64

```
Reads 2 words from virtual address `0xb000_0020`
Expects: `abcdefgh`
```

# test-cartridge-dma.n64

```
DMAs 8 bytes from cartridge address `0x1000_0021`
Expects: `abcdefgh`
```

These all print `PASS` on N64 hardware.
All but `test-cartridge-word.n64` prints `FAIL` on cen64.

**Comment by tj90241** [comment]
Reproducable, small test cases... thank you, fine sir!  I'll look at this tonight... exciting at this seems like a pretty big bug that may be manifesting itself elsewhere, too.
